stages:
- name: Build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: |-
        echo 'cdsb' >test.html
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nginx-pipeline:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
