kind: Service
apiVersion: v1
metadata:
  name: nginx-pipeline-service
spec:
  selector:
    app: nginx-pipeline
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pipeline
  labels:
    app: helloserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pipeline
  template:
    metadata:
      labels:
        app: nginx-pipeline
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: nginx-pipeline
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
